[webconfig]
  enable = true #是否启用网页配置模式

[web]
  root = "/Users/nieaowei/Desktop/blog/public" # 网站根目录
  [web.https]
    enable = false
    filepath = "" # 基于root的路径
  [web.static]
    enable = false # 是否启用单独的静态资源文件夹
    path = ""
